version: '3'

services: 
  app: 
    container_name: 'schedule_api'
    build: .
    command: npm run start
    ports: 
      - '3000:3000'
    volumes: 
      - .:/usr/app

  db:
    container_name: 'schedule_database'
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    restart: always
    ports:
      - '6603:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo

  adminer:
    container_name: 'adminer'
    image: adminer
    restart: always
    ports:
      - 8080:8080
